apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j7e05x1sl-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/j7e05x1sl-dotnet-basic-gitops